### ISSUE TITLE
brainstorm app ideas

### ISSUE THREAD

**Issue by gdumitrescu** [gdumitrescu/hackathon#11]
TODO: Gather ideas for the app and APIs based on themes announced by Koding
### WHAT IS THE THEME FOR THE HACKATHON?

The following themes have been selected:
1. Problems facing our planet, explained using interactive data visualization. (e.g. climate change, earthquakes, food/water waste, etc.)
2. Introducing software development to a beginner (games!)
3. No one reads the fine print (ie TOS, EULA, legal documents) anymore yet every site has them. Devise a creative/interactive solution.
4. HTML5 games that are educational and learning oriented. (multiplayer preferred)
5. Challenges associated with real time communication and translation (Star Trek universal translator anyone?)

Your task is to use publicly available resources (APIs, data sets, graphics, etc.) and your imagination to create a project that addresses one of the themes of the event.

**Comment by gdumitrescu** [comment]
Please submit your theme preference in the next 24-48h
theme5 +1

**Comment by ghost** [comment]
theme 5 +1

**Comment by 3shv** [comment]
theme1 +1
theme5 +1

**Comment by klebervirgilio** [comment]
theme3 +1
theme5 +1

**Comment by gdumitrescu** [comment]
@jet4fire Aleksandr Please submit your theme preference in the next 12h. If you do not respond, we will consider that you no longer want to participate and invite someone else to our team.

**Comment by gdumitrescu** [comment]
Based on your votes, the theme is:
theme5 +4 <<<<<
theme1 +1
theme3 +1
