### ISSUE TITLE
Rajesh-Veeranki bio

### ISSUE THREAD

**Issue by gdumitrescu** [gdumitrescu/hackathon#12]
Please provide a much detail as you can:
- your name?
- why did you decide to participate in the hackathon?
- your skills and what you are going to do as part of the team?
- technologies, APIs you are going to use?
- what kind of application you are going to build?
- add yourself to the team name on https://github.com/koding/global.hackathon from your own Github account.

**Comment by 3shv** [comment]
Name : Rajesh Veeranki
Reason to participate: Learn from others , contribute , fun
Skills: C++ , Javascript, Node.JS , shell scripting . Can contribute as situation demands both front-end and back-end
Technologies: Anything goes
Koding URL: https://koding.com/brood
