### ISSUE TITLE
mailmevenkat bio

### ISSUE THREAD

**Issue by gdumitrescu** [gdumitrescu/hackathon#13]
Please provide a much detail as you can:
- your name?
- why did you decide to participate in the hackathon?
- your skills and what you are going to do as part of the team?
- technologies, APIs you are going to use?
- what kind of application you are going to build?
- add yourself to the team name on https://github.com/koding/global.hackathon from your own Github account.

**Comment by ghost** [comment]
# Info
- Venkateswaran Selvan
- For fun, experience and a good team
- Web technologies (html, css, JS, NodeJS, php) and programming skills (c, c++, core-java, android), I can contribute as both front-end as well as backend developer.
- Koding link - https://koding.com/mailmevenkat25
