### ISSUE TITLE
online chat schedule

### ISSUE THREAD

**Issue by gdumitrescu** [gdumitrescu/hackathon#4]

**Comment by gdumitrescu** [comment]
Gabriel
Toronto, Canada,  UTC-5
- Mon 10pm-12am
-  Tue: 10pm-12am
- Wed: 10pm-12am
- Thu: 10pm-12am
- Fri: 10pm-12am
- Sat: 10pm-12am
- Sun: 10pm-12am

**Comment by fiazhusyn** [comment]
I may not be available at these times due to difference in timezone. What suits me is any time between 7AM to 1PM in UTC-5

**Comment by AleksandrMihhailov** [comment]
Gabriel, my timezone is Europe/Estonia UTC+2 and i can be available at time, which you suggested!

**Comment by ghost** [comment]
I will be available at 9.30 PM to 1 PM (UTC -5). My timezone UTC +5:30 except for these 5 days (Nov - 26, 28. Dec 1,3,5), i won't be online for whole day but can come on and off on those days. Sorry for the inconvenience.

**Comment by klebervirgilio** [comment]
Hey Guys! 
My timeline is GMT-3 (Brazil - São Paulo).

I'd be available 4 pm - 7 pm...

Hard to find time slot... wondering if a service like this: https://gb.youcanbook.me/pricing.jsp can help.

**Comment by gdumitrescu** [comment]
@klebervirgilio I like the idea of a booking time option...
