### ISSUE TITLE
team name suggestions

### ISSUE THREAD

**Issue by gdumitrescu** [gdumitrescu/hackathon#5]
add team name suggestions

**Comment by gdumitrescu** [comment]
Team name was given by Koding as #CommentsOfClicks at https://github.com/koding/global.hackathon

**Comment by gdumitrescu** [comment]
Koding changed today the process for team name information
@jet4fire @klebervirgilio Please suggest a different team name if you want to change the one originally assigned by Kodng (CommentsOfClicks). 
For example, my suggesstion is HackTerrans

**Comment by klebervirgilio** [comment]
What about "[Grok](http://en.wikipedia.org/wiki/Grok)-science"  or "[Grok](http://en.wikipedia.org/wiki/Grok)-Labs"... "Groksh" ??

> Grok means to understand so thoroughly that the observer becomes a part of the observed—to merge, blend, intermarry, lose identity in group experience. It means almost everything that we mean by religion, philosophy, and science—and it means as little to us (because of our Earthling assumptions)  as color means to a blind man.

http://en.wikipedia.org/wiki/Grok

**Comment by ghost** [comment]
HackOwls (like NightOwls, who doesn't sleep all night) or WolfPack (phrase from hangover movie).

**Comment by gdumitrescu** [comment]
Please submit your suggestions and votes in the next 24-48h
CommentsOfClicks
GrokLabs
HackOwls +1
HackTerrans +1
WolfPack

**Comment by ghost** [comment]
GrokLabs +1
HackOwls +1

**Comment by 3shv** [comment]
CommentsOfClicks
GrokLabs 
HackOwls +1
HackTerrans +1
WolfPack

**Comment by klebervirgilio** [comment]
GrokLabs +1
I'd suggest we work with variations too..
Grokers
Grokin'
GrokOwls 
GrokHackers

(I'm not that good with English to think in good variations)

**Comment by gdumitrescu** [comment]
@jet4fire Aleksandr Please submit your suggestion in the next 12h. If you do not respond, we will consider that you no longer want to participate and invite someone else to our team.

**Comment by gdumitrescu** [comment]
Based on your votes, team name is:
HackOwls +3 
GrokLabs +2
HackTerrans +2
